### ISSUE TITLE
System commands are not working in macOS Sierra

### ISSUE THREAD

**Issue by sarathprasath-krishnaswamy** [laconalabs/LaconaApp#151] opened 2017-01-10 05:36 UTC
System Commands like:

1. lock
2. logout
3. restart, etc.,

are not working. Am I missing something. Some permissions I need to grant?

**Comment by brandonhorst** [comment] 2017-01-10 13:55
Could you send me the contents of `/Users/<your user name>/Library/Logs/Lacona/app.log`? If any errors are being reported, I can look into it.

**Comment by brandonhorst** [comment] 2017-02-03 19:55
Unable to reproduce, closing until more information is provided.

**Closed as completed by brandonhorst** 2017-02-03 19:55 UTC
