### ISSUE TITLE
beta 5 crashes on 10.11.3

### ISSUE THREAD

**Issue by scfcode** [laconalabs/LaconaApp#58] opened 2016-02-22 01:59 UTC
Downloaded beta 5 - hoping to try.... Immediately at launch I see a crash dump, briefly summarized

 as

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
abort() called
terminating with uncaught exception of type NSException

---

**Comment by scfcode** [comment] 2016-02-22 02:01
[Lacona_2016-02-21-175148_bali_crash.txt](https://github.com/lacona/LaconaApp/files/140001/Lacona_2016-02-21-175148_bali_crash.txt)

**Comment by brandonhorst** [comment] 2016-02-22 14:25
Interesting. I (and many others) are running it on 10.11.3 just fine. I think I know where this issue may be. If you are willing, could you please try installing Public Beta 3 (0.3) and tell me if it crashes on startup?

http://lacona-download.firebaseapp.com/packages/0.3/LaconaBeta.zip

Also, if my guess about the origin of this problem is correct, you can work around it by **manually moving `Lacona.app` to /Applications`**.

**Comment by ansel1** [comment] 2016-02-23 15:57
I noted the crash too.  Moving to /Applications fixed it.  It was crashing right after the dialog asking whether I wanted to enable automatic updates was displayed.

**Comment by brandonhorst** [comment] 2016-02-23 16:34
OK - so I know where the issue is. I'll make sure this is fixed in the next release. Thank you both!

**Comment by scfcode** [comment] 2016-02-23 23:19
Indeed moving to the /Applications folder avoids the crash.

Keep up the great work and I'll try to test and help if/where I can.

**Comment by brandonhorst** [comment] 2016-02-27 16:42
This _should_ be fixed in 0.5.0, which was [just released](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). I _believe_ that I reproduced your issue correctly and fixed it. If you don't mind, go ahead and give it a shot for me.

If my understanding was correct, it was a conflict between the "Move to /Applications" code and the "Can I enable automatic updates?" code.

I'll close for now, but if the problem still happens with the new build, let me know!

**Closed as completed by brandonhorst** 2016-02-27 16:42 UTC
