### ISSUE TITLE
Allow search window to be moved

### ISSUE THREAD

**Issue by sebj** [laconalabs/LaconaApp#139] opened 2016-11-22 18:59 UTC
Spotlight allows the search window to be moved anywhere on screen, which is useful when looking up/checking something from an open app you don't want to obscure. Would be great to able to do that with Lacona.

**Comment by brandonhorst** [comment] 2016-11-23 19:39
Duplicate of https://github.com/laconalabs/LaconaApp/issues/3

**Closed as completed by brandonhorst** 2016-11-23 19:39 UTC
