### ISSUE TITLE
Window opening only in desktop

### ISSUE THREAD

**Issue by whit-colm** [laconalabs/LaconaApp#156] opened 2017-02-03 16:40 UTC
When I trigger Lacona, it only opens in my desktop, even if I am in a different fullscreen app (for instance, Safari.) I am running a beta so I do not know if this is an issue caused by that, but either way, I feel it is important for you guys to know.

Also, sweet app!

**Comment by brandonhorst** [comment] 2017-02-03 19:46
Thanks! Duplicate of https://github.com/laconalabs/LaconaApp/issues/42.

**Closed as completed by brandonhorst** 2017-02-03 19:46 UTC
