### ISSUE TITLE
Not a fan of the new theme

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#27] opened 2016-02-01 14:07 UTC
<img width="898" alt="screen shot 2016-02-01 at 8 55 21 am" src="https://cloud.githubusercontent.com/assets/6983821/12719425/f1e01500-c8c2-11e5-9153-a27113282d7a.png">

The white borders are too bright, and the colors are dull. I think One Dark could work, but different colors need to be picked.

**Comment by luispedrofonseca** [comment] 2016-02-01 14:18
Yeah, I liked the original one better. Can't exactly pinpoint what's different though.

**Comment by brandonhorst** [comment] 2016-02-01 14:52
I agree that the placeholder borders are a bit bold. I can tweak that down.

**Comment by brandonhorst** [comment] 2016-02-01 14:55
This is actually a pretty tricky problem to solve. An important design consideration is that I want the colors to be mostly the same in light and dark mode, so that if you switch themes, every argument still looks as you would expect it to. Of course, the brightness/lightness levels will be changing, but I want the hue (at least the perceived hue) to stay pretty consistent.

The problem is that the dark background favors more bold colors, and the lighter background favors more reserved colors, and even if you adjust the brightness/lightness, it still looks a bit off. The "Atom One" color scheme looks great in light mode (which is why I selected it - even though Dark Mode was the first release, most people will likely be using light mode most of the time), but I agree the Dark Mode is lacking. If anyone could suggest a color scheme, I'd be happy to try it out! You can try things out in the CSS inspector on the website, or just send me a link and I'll throw together a mockup and post it here.

I value your feedback!

**Comment by brandonhorst** [comment] 2016-02-07 19:09
As of [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md), fallthrough commands no longer get a border, which I find reduces the visual complexity significantly and makes the dark theme much more attractive. I will likely continue tweaking the default themes over time, but I'm going to close this issue out for now. If anyone has specific recommendations about theme changes, please open a new issue and we will discuss them independently. Thanks.

**Closed as completed by brandonhorst** 2016-02-07 19:09 UTC
