### ISSUE TITLE
Can't open google chrome

### ISSUE THREAD

**Issue by asportnoy** [laconalabs/LaconaApp#171] opened 2017-08-12 17:52 UTC
![screen shot 2017-08-12 at 12 51 11 pm](https://user-images.githubusercontent.com/14863373/29243102-ff7a8b30-7f5c-11e7-815a-9b1cd5605787.png)
Please fix

**Comment by brandonhorst** [comment] 2017-09-23 15:25
Duplicate of https://github.com/laconalabs/LaconaApp/issues/166. Will be fixed.

**Closed as completed by brandonhorst** 2017-09-23 15:25 UTC
