### ISSUE TITLE
Open Finder App doesn't work with Lacona

### ISSUE THREAD

**Issue by jbyeung** [laconalabs/LaconaApp#43] opened 2016-02-08 16:33 UTC
I use Spotlight as a terminal for opening apps with just kb.  I can't open Finder, it never finds the Finder in Applications (still does find things like Xcode though).

**Comment by jbyeung** [comment] 2016-02-08 18:14
This is likewise with many other applications.  Is it not searching the Applications folder for app names?

**Comment by brandonhorst** [comment] 2016-02-08 18:20
Fun fact - Finder doesn't actually live in the `/Applications` folder. It lives in `/System/Library/CoreServices`. Therefore, this is the same cause as https://github.com/lacona/LaconaApp/issues/21
It should be fixed with the introduction of the Settings page in the next release or two.

Is Lacona not finding apps that _do_ live in your `/Applications` folder? If so, that's a new issue that we'll need to work out.

**Comment by jbyeung** [comment] 2016-02-08 20:20
Appreciate the feedback and interaction with your users.

Yes, there are some items in /Applications that it doesn't find.  For instance, I have the OSX Slack app in there that is picked up by Spotlight.

**Comment by brandonhorst** [comment] 2016-02-08 21:10
Hmmm... I have Slack and it finds it just fine. However, in testing I did find that certain apps crapped out of the list occasionally. Not sure if it's a spotlight bug that I need to mitigate, or a bug on my end.

Let's be honest, probably the latter.

I'll look into it. Thanks for the report.

**Comment by brandonhorst** [comment] 2016-02-08 22:45
If you get a chance, could you go to your terminal and run this command:

``` sh
mdls /Applications/Slack.app | pbcopy
```

Then send me the contents of your clipboard. Thanks.

**Comment by jbyeung** [comment] 2016-02-08 23:15
Actually on my home computer, Slack works.  But other apps don't work, like
Bluestacks here.  Slack wasn't coming up for my work computer.

Here's the mdls for Bluestacks for me:

_kMDItemOwnerUserID            = 0
kMDItemAlternateNames          = (
    "BlueStacks.app"
)
kMDItemCFBundleIdentifier      = "com.bluestacks.BlueStacks"
kMDItemContentCreationDate     = 2015-07-30 21:45:41 +0000
kMDItemContentModificationDate = 2015-07-30 21:45:41 +0000
kMDItemContentType             = "com.apple.application-bundle"
kMDItemContentTypeTree         = (
    "com.apple.application-bundle",
    "com.apple.application",
    "public.executable",
    "com.apple.localizable-name-bundle",
    "com.apple.bundle",
    "public.directory",
    "public.item",
    "com.apple.package"
)
kMDItemCopyright               = "Copyright © 2015 BlueStack Systems, Inc.
All rights reserved."
kMDItemDateAdded               = 2015-01-01 00:08:36 +0000
kMDItemDisplayName             = "BlueStacks"
kMDItemExecutableArchitectures = (
    "x86_64"
)
kMDItemFSContentChangeDate     = 2015-07-30 21:45:41 +0000
kMDItemFSCreationDate          = 2015-07-30 21:45:41 +0000
kMDItemFSCreatorCode           = ""
kMDItemFSFinderFlags           = 0
kMDItemFSHasCustomIcon         = (null)
kMDItemFSInvisible             = 0
kMDItemFSIsExtensionHidden     = 1
kMDItemFSIsStationery          = (null)
kMDItemFSLabel                 = 0
kMDItemFSName                  = "BlueStacks.app"
kMDItemFSNodeCount             = 1
kMDItemFSOwnerGroupID          = 0
kMDItemFSOwnerUserID           = 0
kMDItemFSSize                  = 283395031
kMDItemFSTypeCode              = ""
kMDItemKind                    = "Application"
kMDItemLanguages               = (
    ar,
    Base,
    cs,
    da,
    de,
    el,
    en,
    "es-MX",
    es,
    fi,
    fr,
    hr,
    hu,
    id,
    it,
    ja,
    ko,
    nb,
    nl,
    pl,
    "pt-PT",
    pt,
    ro,
    ru,
    sk,
    sv,
    th,
    tr,
    vi,
    "zh-Hans",
    "zh-Hant"
)
kMDItemLogicalSize             = 283395031
kMDItemPhysicalSize            = 284495872
kMDItemVersion                 = "0.9.30"

**Comment by brandonhorst** [comment] 2016-02-10 05:48
Found the cause - it's a Lacona bug. It will be fixed in 0.4.1, launching tomorrow. Sorry about that!

**Comment by jbyeung** [comment] 2016-02-10 11:42
Thanks!  Was one major impediment to adopting this over other solutions.

**Comment by brandonhorst** [comment] 2016-02-11 04:36
Implemented in [0.4.1](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). This should both fix the "apps don't always appear" bug, and ensure that Finder is displayed properly. Thanks for the report!

**Closed as completed by brandonhorst** 2016-02-11 04:36 UTC

**Comment by jbyeung** [comment] 2016-02-11 15:36
No, thank you for actually taking these bug reports and fixing them!  Glad
to have foudn my Flashlight replacement!
